### ISSUE TITLE
Support Ironwood

### ISSUE THREAD

**Issue by hoaivan** [appsembler/figures#103]
It seems that figures not yet support Ironwood. Any guidances to implement it please? I want to contribute if possible.

**Comment by johnbaldwin** [comment]
Hey, @hoaivan 
sorry for the long silence.  Right now I'm focused on bug fixing for Hawthorn to push out version 0.3.0 (currently we're at 0.3.0prereleasae).

Feel free to try Figures on ironwood and report any specific errors you find. That help us move forward. We want this to be a community driven project. 

Regis Behmo is one developer who is contributing to help Figures. He has created a Tutor plugin (https://pypi.org/project/tutor-figures/). I've heard that is runs on Ironwood, but haven't tried it yet myself.

**Comment by antoineselim** [comment]
We are trying it on Ironwood. Although we have the list of participants when exploring specific courses, there is enrollment data for any course, they all appear as zero on the main dashboard (see screencap)

[
![Capture](https://user-images.githubusercontent.com/18268504/62462637-2d013580-b788-11e9-8a6c-bb1e097104cb.PNG)
](url)

**Comment by antoineselim** [comment]
We are trying it on Ironwood.
![Capture](https://user-images.githubusercontent.com/18268504/62462976-18716d00-b789-11e9-890a-9132c8883dcc.PNG)

Although we can see the list of participants when we click for the course details, all enrollment data is zero for all courses on the main dashboard.

**Comment by peeushb** [comment]
Hi Antoine Selim - I am trying to install figures on my ironwood release as well, but running into errors  - can you please share your install steps? Below is what I tried:
1. Installed rc-2 release: pip install https://github.com/appsembler/figures/archive/0.3.0-prerelease2.zip
2. Added Figures to the installed apps in the LMS settings: included below in my lms.envs.json file:
"ADDL_INSTALLED_APPS": [
    "figures"
],
3. Added Figures to the LMS settings: At the bottom of the lms/envs/production.py file, added the following:
if 'figures' in INSTALLED_APPS:
    import figures
    figures.update_settings(
        WEBPACK_LOADER,
        CELERYBEAT_SCHEDULE,
        ENV_TOKENS.get('FIGURES', {}))
4. Added Figures to the LMS URLconf: At the bottom of the lms/urls.py file, added the following:
if 'figures' in settings.INSTALLED_APPS:
        urlpatterns += (
                url(r'^figures/',
                    include('figures.urls', namespace='figures')),
        )
5. Tried to run migrations to include Figures models:  sudo -u edxapp /edx/bin/python.edxapp /edx/bin/manage.edxapp lms --settings=production migrate Figures
This fails with error: ImportError: No module named figures

Please advise.

**Comment by manish-arch** [comment]
> Hey, @hoaivan
> sorry for the long silence. Right now I'm focused on bug fixing for Hawthorn to push out version 0.3.0 (currently we're at 0.3.0prereleasae).
> 
> Feel free to try Figures on ironwood and report any specific errors you find. I assume that installation on Ironwood would be the same as for Hawthorn. If you can try that out, that would be great and help us move forward! We want this to be a community driven project.
> 
> Regis Behmo is one developer who is contributing to help Figures. He has created a Tutor plugin (https://pypi.org/project/tutor-figures/). I've heard that is runs on Ironwood, but haven't tried it yet my

**Comment by manish-arch** [comment]
File "/home/manish/lm/apps/edx/edx-platform/lms/envs/bitnami.py", line 39, in <module>
    figures.update_settings(
AttributeError: 'module' object has no attribute 'update_settings'

I am getting this error and i am using ironwood on bitnami

**Comment by icanscream** [comment]
Hi @manish-arch :

Does Figures have full Ironwood support? If i follow the official installation steps i get a "Duplicate labels" error.

**Comment by 0xbs0d** [comment]
I'm having the same error as @icanscream.

**Comment by 0xbs0d** [comment]
I spent some time trying to figure this out. I followed the install guide and I tried to debug the thing on my own. When I run
`./manage.py lms migrate figures`

I'm getting
```
WARNING:py.warnings:/opt/edx-ironwood.2-11/apps/edx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2021-01-11 11:14:47,124 WARNING 657802 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2021-01-11 11:14:47,219 WARNING 657802 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
Traceback (most recent call last):
  File "manage.py", line 123, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/edx-ironwood.2-11/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/edx-ironwood.2-11/apps/edx/edx-platform/lms/urls.py", line 1056, in <module>
    urlpatterns.extend(plugin_urls.get_patterns(plugin_constants.ProjectType.LMS))
  File "/opt/edx-ironwood.2-11/apps/edx/edx-platform/openedx/core/djangoapps/plugins/plugin_urls.py", line 22, in get_patterns
    for url_module_path, url_config in _iter_plugins(project_type)
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/edx-ironwood.2-11/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/src/figures/figures/urls.py", line 10, in <module>
    from figures import views
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/src/figures/figures/views.py", line 45, in <module>
    from figures.filters import (
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/src/figures/figures/filters.py", line 34, in <module>
    from figures.pipeline.course_daily_metrics import get_enrolled_in_exclude_admins
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/src/figures/figures/pipeline/course_daily_metrics.py", line 26, in <module>
    from figures.compat import GeneratedCertificate, StudentModule
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/src/figures/figures/compat.py", line 39, in <module>
    from lms.djangoapps.courseware.models import StudentModule  # noqa pylint: disable=unused-import,import-error
  File "/opt/edx-ironwood.2-11/apps/edx/edx-platform/lms/djangoapps/courseware/models.py", line 74, in <module>
    class StudentModule(models.Model):
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/db/models/base.py", line 319, in __new__
    new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
  File "/opt/edx-ironwood.2-11/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/apps/registry.py", line 224, in register_model
    (model_name, app_label, app_models[model_name], model))
RuntimeError: Conflicting 'studentmodule' models in application 'courseware': <class 'courseware.models.StudentModule'> and <class 'lms.djangoapps.courseware.models.StudentModule'>.
```

I would appreciate any nudge in the right direction. Thank you.
