### ISSUE TITLE
to run figures frontend app

### ISSUE THREAD

**Issue by neerajkumarsingh17** [appsembler/figures#376]
## Expected Behavior
> frontend@0.1.0 start /edx/src/figures/frontend
> node scripts/start.js

EACCES: permission denied, open 'webpack-stats.json'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /edx/app/edxapp/.npm/_logs/2021-06-15T09_12_26_848Z-debug.log
edxapp@lms:/edx/src/figures/frontend$ sudo npm

and 
2021-06-15 09:54:19,206 ERROR 43 [django.request] [user None] log.py:228 - Internal Server Error: /figures/
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/webpack_loader/loader.py", line 25, in load_assets
    with open(self.config['STATS_FILE'], encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/edx/src/figures/figures/static/figures/rb16/webpack-stats.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/src/figures/figures/views.py", line 127, in figures_home
    return render(request, 'figures/index.html', context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/classytags/core.py", line 154, in render
    return self.render_tag(context, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/sekizai/templatetags/sekizai_tags.py", line 88, in render_tag
    rendered_contents = nodelist.render(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
    tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/webpack_loader/utils.py", line 62, in get_as_tags
    bundle = _get_bundle(bundle_name, extension, config)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/webpack_loader/utils.py", line 40, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/webpack_loader/loader.py", line 59, in get_bundle
    assets = self.get_assets()
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/webpack_loader/loader.py", line 38, in get_assets
    return self.load_assets()
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/webpack_loader/loader.py", line 31, in load_assets
    self.config['STATS_FILE']))
OSError: Error reading /edx/src/figures/figures/static/figures/rb16/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?
[15/Jun/2021 09:54:19] "GET /figures/ HTTP/1.1" 500 452395

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by neerajkumarsingh17** [comment]
In the Open edX Juniper version in local how to install figures, please suggest any doc or provide me like anyone done this type of work.
#openedx #370 @thraxil @thraxil @thraxil @natea @johnbaldwin @johnbaldwin
